### ISSUE TITLE
Python error on Mac OS 10.15 and QGIS 3.10

### ISSUE THREAD

**Issue by Marcus-Vitruvius** [t-systems-on-site-services-gmbh/geoCore#43]
I got this python error after using the plugin on the example files (I linked both files in QGIS)
both on selecting a single core and the entire layer
             TypeError: unsupported operand type(s) for -: 'str' and 'str'

full log
             
2021-06-16T12:18:27     WARNING    Traceback (most recent call last):
              File "/Users/wouter/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 157, in showEvent
              self.drawProfilesNorthSouth()
              File "/Users/wouter/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 277, in drawProfilesNorthSouth
              self._drawProfiles(crit)
              File "/Users/wouter/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoCore/petroProfile_dialog.py", line 303, in _drawProfiles
              pac = builder.getProfilesAndConnectors(features)
              File "/Users/wouter/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoCore/profileBuilder.py", line 98, in getProfilesAndConnectors
              profiles.append(self._getProfile(f.attribute("id"), xp * 100, yp))
              File "/Users/wouter/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoCore/profileBuilder.py", line 137, in _getProfile
              pb.height = l[self.config.settings["depthTo"]]-l[self.config.settings["depthFrom"]]
             TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by gricklom** [comment]
Hello Marcus,

Could you please open the properties of the layer corings data in QGIS and let me know which type and type name of the fields 6 (tiefe von) and 7 (tiefe bis)? I suspect it shows QString/text instead of integer or double.

Best regards,
Gerrit

**Comment by Marcus-Vitruvius** [comment]
I have changed them to double, error remains

**Comment by Marcus-Vitruvius** [comment]
Error is part of QGIS itself. in version 3.14 the bug of the "change in field type" has been fixed.
It works now, thanks.

kind regards

**Comment by gricklom** [comment]
Hello Marcus,

Happy to hear that it's working now.

Kind regards,
Gerrit
